language: python
python:
  - "3.6"
  - "3.7"

notifications:
  email: false

install:
    - pip install -q cython coverage coveralls
    - python setup.py develop

script:
  - cython -a timeset/timeset.pyx
  - python3 setup.py build_ext --inplace
  - coverage run --source timeset setup.py test
  -
after_success:
    coveralls
